# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: e2e-cypress

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Install Node 23
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'
      
      - name: install yarn
        run : | 
          npm install -g yarn@1.22

      - name: run test
        run : |
          yarn test

      - name: Generate Report
        run: |
          yarn report

      - name: Upload Artifact Report
        if: always()
        with:
          name: cypress-video
          path: reports
        

    

    

      
