name: e2e-cypress

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Install Node 23
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'
      
      - name: install depedencies
        run : | 
          npm install -g yarn@1.22
          yarn install

      - name: run test
        run : |
          yarn test

      - name: Generate Report
        run: |
          yarn report

      - name: Upload Artifact Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress report
          path: reports
        

    

    

      
